#
#-----------------------------
#COMMON INSTALLATIONs
#-----------------------------
#
- hosts: ansible
  remote_user: jbus
  tasks:
  - name: download jdk file
    get-url: url=https://jkbdevops.blob.core.windows.net/files/jdk-7u75-linux-x64.tar.gz dest=filearchives/jdk-7u75-linux-x64.tar.gz

  - name: download Cloudera Install File
    get_url: url= https://jkbdevops.blob.core.windows.net/files/hadoop-2.3.0-cdh5.1.2.tar.gz dest=filearchives/hadoop-2.3.0-cdh5.1.2.tar.gz

- hosts: allnodes
  remote_user: root
  roles:
    - disable_sel
    - commons
    - ssh_known_hosts
	- jdk
	- ntp


#
#-----------------------------
# HADOOP CLUSTER SETUP
#-----------------------------
#


- hosts: hadoopcluster
  remote_user: root
  roles:
    - ssh_password_less
    - cdh5_hadoop_commons_tarball

- hosts: namenodes
  remote_user: root
  roles:
    - cdh5_hadoop_namenode_active

- hosts: secondarynamenode
  remote_user: root
  roles:
    - cdh5_hadoop_sec_namenode

- hosts: resourcemanager
  remote_user: root
  roles:
    - cdh5_hadoop_resourcemgr

- hosts: datanodes
  remote_user: root
  roles:
    - cdh5_hadoop_datanode

#
# Creating a Storm User on Namenode/ This will eventually be a edge node.
#
- hosts: namenodes
  remote_user: root
  roles:
    - post_install_setups


