# file: roles/bind/tasks/main.yml

- name: Install the sql package.
  yum: name=mysql-server state=latest

- name: Stop mysql service.
  service: name=mysqld state=stopped

- name: Rename the existing conf file.
  command: mv /etc/my.cnf /etc/my.cnf.old 

- name: Copy the new conf file.
  template: src=my.cnf dest=/etc/
  
- name: Start mysql service and set to start on boot.
  service: name=mysqld state=started enabled=yes

- name: Update MySQL root password for localhost root account (5.7.x).
  shell: >
    mysql -u root -NBe
    'CREATE USER "jbus"@"%" IDENTIFIED BY "SprPassw0rd123";GRANT ALL PRIVILEGES ON *.* TO "jbus"@"%" WITH GRANT OPTION;'