---

  - name: Updating Configuration File in Zookeeper.
    template: src={{ item }} dest={{ common['soft_link_base_path'] }}/hadoop/etc/hadoop/  owner={{ hadoop_user }} group={{ hadoop_group }}
    with_items:
      - core-site.xml
      - hdfs-site.xml
      - yarn-site.xml
      - slaves
      - mapred-site.xml
      - hadoop-env.sh
