# file: roles/mysql/tasks/main.yml

- name: Install the CD Plugins.
  command: rpm -i /home/jbus/cloudera-director-plugins-2.1.0-1.director210beta2.p0.47.el6.x86_64.rpm

- name: Install the CD Client.
  command: rpm -i /home/jbus/cloudera-director-client-2.1.0-1.director210beta2.p0.47.el6.x86_64.rpm

- name: Install redhat-lsb
  yum: name=redhat-lsb state=latest  

- name: Copy and UnArchive the Azure Plugin Package.
  unarchive: creates=/var/lib/cloudera-director-plugins/azure-provider-1.0.0-beta_nielsen.3 dest=/var/lib/cloudera-director-plugins/ src=/home/jbus/azure-provider-1.0.0-beta_nielsen.3.tar.gz

- name: Remove old Azure Plugin
  command: rm -Rf /var/lib/cloudera-director-plugins/azure-provider-1.0.0-beta.2
  
- name: Start Cloudera Director service and set to start on boot.
  service: name=cloudera-director-server state=started enabled=yes