---

 - name: Create `namenode` data directory
   file: path={{ item }}{{ hadoop_hdfs.dfs_dir_namenode }} owner={{ hadoop_user }} group={{ hadoop_group }} state=directory
   with_items: hadoop_hdfs.dfs_dir_parent

 - name: Create `secondary namenode` data directory
   file: path={{ item }}{{ hadoop_hdfs.dfs_dir_sec_namenode }} owner={{ hadoop_user }} group={{ hadoop_group }} state=directory
   with_items: hadoop_hdfs.dfs_dir_parent
 
 - name: Format the namenode - [[ WILL NOT FORMAT IF current/VERSION]].
   command: creates={{ hadoop_hdfs.dfs_dir_parent[0]  }}{{ hadoop_hdfs.dfs_dir_namenode }}/current/VERSION sh {{ common['soft_link_base_path'] }}/hadoop/bin/hadoop namenode -format
   sudo: yes
   sudo_user: "{{ hadoop_user }}"

 - name: Starting Namenode.
   command: sh {{ common['soft_link_base_path'] }}/hadoop/sbin/hadoop-daemon.sh start namenode
   sudo: yes
   sudo_user: "{{ hadoop_user }}"
