---
- name: Check hosts file
  remote_user: root
  tags: check
  hosts: all
  roles:
    - check_config

- name: Setup local environment
  remote_user: root
  tags:
    - common
    - clinit
    - interfaces
    - config
  hosts: all
  tasks:
    - name: create working directory
      local_action: file dest="{{ inventory_dir }}/workdir" state=directory
      run_once: true

- name: Prepare hosts for cloudera hadoop cluster
  remote_user: root
  tags: common
  hosts: java
  roles:
    - common

- name: Deploy zookeeper
  remote_user: root
  hosts: zookeepernodes
  tags: zookeepernodes
  roles:
    - zookeeper

- name: Deploy hadoop configuration
  remote_user: root
  tags:
    - config
    - hadoop
  hosts: hadoop
  roles:
    - hadoop

- name: Deploy journal nodes
  remote_user: root
  tags: journalnodes
  hosts: journalnodes
  tasks:
    - include: roles/hadoop/tasks/journalnode.yaml

- name: Deploy namenodes
  remote_user: root
  tags: namenodes
  hosts: namenodes
  tasks:
    - include: roles/hadoop/tasks/namenode.yaml
    - include: roles/hadoop/tasks/namenodes-fence.yaml
      when: groups['namenodes']|count > 1

- name: Deploy datanodes
  remote_user: root
  tags: datanodes
  hosts: datanodes
  tasks:
    - include: roles/hadoop/tasks/datanode.yaml

- name: Test hdfs
  remote_user: root
  tags: test
  hosts: namenodes
  tasks:
    - include: roles/hadoop/tasks/test-hdfs.yaml

- name: Deploy yarn resource manager and job history server
  remote_user: root
  tags: yarnresourcemanager
  hosts: yarnresourcemanager
  tasks:
    - include: roles/hadoop/tasks/resourcemanager.yaml

- name: Test mapreduce
  remote_user: root
  tags: test
  hosts: yarnresourcemanager
  tasks:
    - include: roles/hadoop/tasks/test-mapreduce.yaml

- name: Deploy postgresql
  remote_user: root
  tags: postgresql
  hosts: postgresql
  roles:
    - postgresql

- name: Deploy hive metastore
  remote_user: root
  tags: hivemetastore
  hosts: hivemetastore
  roles:
    - hivemetastore

- name: Deploy hive client on datanodes
  remote_user: root  tags: hive
  hosts: datanodes
  tasks:
    - include: roles/hivemetastore/tasks/hive-client.yaml
      when: groups['hivemetastore']|count == 1

- name: Deploy impala state-store and catalog
  remote_user: root
  tags: impala
  hosts: impala-store-catalog
  roles:
    - impala

- name: Deploy impala daemon on datanodes
  remote_user: root
  tags: impala
  hosts: datanodes
  tasks:
    - include: roles/impala/tasks/impala-server.yaml
      when: groups['impala-store-catalog']|count == 1

- name: Deploy HBase
  remote_user: root
  tags: hbase
  hosts: hbasemaster
  roles:
    - hbase

- name: Deploy HBase regionservers on datanodes
  remote_user: root
  tags: hbase
  hosts: datanodes
  tasks:
    - include: roles/hbase/tasks/regionserver.yaml
      when: groups['hbasemaster']|count == 1

- name: Deploy spark
  remote_user: root
  tags: spark
  hosts: spark
  roles:
    - spark

- name: Deploy solr search
  remote_user: root
  tags: solr
  hosts: solr
  roles:
    - solr

- name: Deploy oozie
  remote_user: root
  tags: oozie
  hosts: oozie
  roles:
    - oozie

- name: Deploy kafka
  remote_user: root
  tags: kafka
  hosts: kafka
  roles:
    - kafka

- name: Deploy Hue
  remote_user: root
  tags: hue
  hosts: hue
  roles:
    - hue

- name: Deploy snmp monitoring
  remote_user: root
  tags: snmp
  hosts: java
  roles:
    - { role: snmp, when: enable_snmp }

- name: Deploy syslog-ng monitoring
  remote_user: root
  tags: syslog
  hosts: java
  roles:
    - { role: syslog-ng, when: enable_syslog }

- name: cluster
  remote_user: root
  tags: cluster
  hosts: yarnresourcemanager
  tasks:
    - debug: msg="{{ lookup('pipe', 'echo; clinit -S workdir/services.xml --nocolors tree;echo =')}}"
      run_once: true

- name: dashboard
  remote_user: root
  tags: dashboard
  hosts: dashboard
  roles:
    - dashboard
